
name: deploy-docs

on:
  push:
    branches:
      - 'main'

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install -U jupyter-book
    # Build the book
    - name: Build the docs
      run: |
        jupyter-book clean docs
        jupyter-book build docs
    - name: Create cname file
      uses: finnp/create-file-action@master
      env:
        FILE_NAME: "./docs/_build/html/CNAME"
        FILE_DATA: "unhide-docs.helmholtz-metadaten.de"

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
